# Use the official MySQL 8.0 image from Docker Hub
FROM mysql:8.0

# Set the root password for MySQL
ENV MYSQL_ROOT_PASSWORD=admin

# Create a new database
ENV MYSQL_DATABASE=tncalculatordb

# Expose the default MySQL port
EXPOSE 3306
